#!/usr/bin/env bash
# Prepare a fresh checkout: secrets directory, config files, data directories and
# the generated vault mounts. Idempotent. Never uses sudo and never prints secrets.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo"

say() { printf '  %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

env_file="${PENNYWORTH_ENV_FILE:-.env}"
[ -f "$env_file" ] || { cp .env.example "$env_file"; die "$env_file created from .env.example; edit it, then re-run."; }
set -a; . "$env_file"; set +a
config_dir="${PENNYWORTH_CONFIG_DIR:-config}"
vault_file="${COMPOSE_VAULT_FILE:-compose.vault.yaml}"

: "${PENNYWORTH_SECRETS_DIR:?set in .env}" "${TRANSCRIPTS_DIR:?set in .env}" "${VAULT_DIR:?set in .env}" "${VAULT_FOLDERS:?set in .env}"
case "$PENNYWORTH_SECRETS_DIR" in "$repo"*) die "PENNYWORTH_SECRETS_DIR must be outside the repository";; esac

echo "Checking prerequisites"
command -v docker >/dev/null || die "docker not found"
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found"
command -v node >/dev/null || die "node (>= 24) not found; it runs scripts/paperclip-setup.mjs"
if docker info --format '{{.SecurityOptions}}' 2>/dev/null | grep -q rootless; then
  say "docker: rootless"
else
  say "docker: rootful (see nix/README.md to switch to rootless Docker)"
fi
[ -d "$TRANSCRIPTS_DIR" ] || die "TRANSCRIPTS_DIR does not exist: $TRANSCRIPTS_DIR"
[ -d "$VAULT_DIR" ] || die "VAULT_DIR does not exist: $VAULT_DIR"

echo "Secrets: $PENNYWORTH_SECRETS_DIR"
umask 077
mkdir -p "$PENNYWORTH_SECRETS_DIR"
chmod 0700 "$PENNYWORTH_SECRETS_DIR"
gen_secret() { # name
  local f="$PENNYWORTH_SECRETS_DIR/$1"
  if [ ! -s "$f" ]; then
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$f"
    say "generated $1"
  fi
}
placeholder() { # name content
  local f="$PENNYWORTH_SECRETS_DIR/$1"
  [ -e "$f" ] || { printf '%s' "$2" > "$f"; say "created placeholder $1"; }
}
gen_secret paperclip_auth_secret
gen_secret paperclip_agent_jwt_secret
gen_secret ops_mcp_token
gen_secret google_mcp_token
placeholder paperclip_ops_key ""
placeholder google_oauth.json "{}"
chmod 0600 "$PENNYWORTH_SECRETS_DIR"/*

echo "Config"
mkdir -p "$config_dir"
for f in system routing paperclip; do
  [ -f "$config_dir/$f.yaml" ] || { cp "config/$f.example.yaml" "$config_dir/$f.yaml"; say "created $config_dir/$f.yaml"; }
done
grep -q 'names: \[\]' "$config_dir/system.yaml" && say "edit self.names/self.emails in $config_dir/system.yaml"

echo "Data"
data="${PENNYWORTH_DATA_DIR:-./data}"
mkdir -p "$data/paperclip" "$data/ops-mcp"
umask 022

echo "Vault mounts"
IFS=',' read -r -a folders <<< "$VAULT_FOLDERS"
{
  echo "# Generated by scripts/bootstrap.sh from VAULT_FOLDERS. Do not edit; re-run bootstrap."
  echo "services:"
  echo "  ops-mcp:"
  echo "    volumes:"
  for raw in "${folders[@]}"; do
    f="$(echo "$raw" | sed 's#^/*##; s#/*$##')"
    [ -n "$f" ] || continue
    case "$f" in *..*|.*) die "invalid vault folder: $f";; esac
    if [ ! -d "$VAULT_DIR/$f" ]; then
      mkdir -p "$VAULT_DIR/$f"   # created as you, so Docker never creates it as root
      say "created vault folder $f" >&2
    fi
    printf '      - "%s:/vault/%s"\n' "$VAULT_DIR/$f" "$f"
  done
} > "$vault_file"
say "wrote $vault_file (${#folders[@]} folders)"

echo "Installing setup-script dependency"
[ -d services/ops-mcp/node_modules/yaml ] || npm ci --prefix services/ops-mcp --silent

echo "Validating compose"
docker compose --env-file "$env_file" -f compose.yaml -f "$vault_file" config --quiet
echo "Done. Next: docker compose up -d --build, then node scripts/paperclip-setup.mjs"
